amend test file 2
hello from main
# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.aapt2FromMavenOverride=/data/data/com.jahangir/files/usr/bin/aapt2
# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.daemon=null
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
android.aapt2FromMavenOverride=/data/data/com.jahangir/files/usr/bin/aapt2
